# Generated by Django 4.0.2 on 2022-02-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_price_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='in_active',
            new_name='is_active',
        ),
    ]
